"""add_consent_log_table

Revision ID: 0bb131b95781
Revises: a9dd4ed1645b
Create Date: 2026-05-09 17:41:38.735322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb131b95781'
down_revision: Union[str, Sequence[str], None] = 'a9dd4ed1645b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CONSENT_LOG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_kyc_id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('declaration_version', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_kyc_id'], ['CUSTOMER_KYC.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CONSENT_LOG_id'), 'CONSENT_LOG', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CONSENT_LOG_id'), table_name='CONSENT_LOG')
    op.drop_table('CONSENT_LOG')
    # ### end Alembic commands ###
