"""auto_20260511_220332

Revision ID: 25f9a8412a76
Revises: c307374004d7
Create Date: 2026-05-11 22:03:37.359895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f9a8412a76'
down_revision: Union[str, Sequence[str], None] = 'c307374004d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OWNER_KYC', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('OWNER_KYC', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('OWNER_KYC', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.drop_column('OWNER_KYC', 'address_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OWNER_KYC', sa.Column('address_3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('OWNER_KYC', 'zip_code')
    op.drop_column('OWNER_KYC', 'state')
    op.drop_column('OWNER_KYC', 'city')
    # ### end Alembic commands ###
