"""auto_20260512_145525

Revision ID: 40c87c9bc360
Revises: 25f9a8412a76
Create Date: 2026-05-12 14:55:27.929690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c87c9bc360'
down_revision: Union[str, Sequence[str], None] = '25f9a8412a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AVAILABILITY',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BOOKED', 'CANCELLED', name='availabilitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fleet_id'], ['FLEET.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_id', 'date', name='uq_fleet_date')
    )
    op.create_index(op.f('ix_AVAILABILITY_id'), 'AVAILABILITY', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_AVAILABILITY_id'), table_name='AVAILABILITY')
    op.drop_table('AVAILABILITY')
    # ### end Alembic commands ###
