"""auto_20260511_215844

Revision ID: 5c8ef3ac5d6d
Revises: 7f06dc1a06ed
Create Date: 2026-05-11 21:58:47.120620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8ef3ac5d6d'
down_revision: Union[str, Sequence[str], None] = '7f06dc1a06ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FLEET', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('FLEET', sa.Column('max_load_capacity', sa.Float(), nullable=True))
    op.add_column('FLEET', sa.Column('dimensions', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FLEET', 'dimensions')
    op.drop_column('FLEET', 'max_load_capacity')
    op.drop_column('FLEET', 'description')
    # ### end Alembic commands ###
