"""auto_20260512_182333

Revision ID: 622d4f8c37b0
Revises: 658bd1a55290
Create Date: 2026-05-12 18:23:37.178698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622d4f8c37b0'
down_revision: Union[str, Sequence[str], None] = '658bd1a55290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BOOKING',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_kyc_id', sa.Integer(), nullable=False),
    sa.Column('availability_id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.Column('pickup_address', sa.String(length=500), nullable=False),
    sa.Column('destination_address', sa.String(length=500), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('goods_type', sa.String(length=200), nullable=False),
    sa.Column('goods_weight_kg', sa.Float(), nullable=False),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('owner_response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['availability_id'], ['AVAILABILITY.id'], ),
    sa.ForeignKeyConstraint(['customer_kyc_id'], ['CUSTOMER_KYC.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['FLEET.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BOOKING_id'), 'BOOKING', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BOOKING_id'), table_name='BOOKING')
    op.drop_table('BOOKING')
    # ### end Alembic commands ###
