"""auto_20260510_162519

Revision ID: 71c2e3ff6c14
Revises: d4e5f6a7b8c9
Create Date: 2026-05-10 16:25:22.344821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c2e3ff6c14'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FLEET', sa.Column('rc_expiry_date', sa.Date(), nullable=True))
    op.add_column('FLEET', sa.Column('insurance_expiry_date', sa.Date(), nullable=True))
    op.add_column('FLEET', sa.Column('permit_expiry_date', sa.Date(), nullable=True))
    op.add_column('FLEET', sa.Column('puc_expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FLEET', 'puc_expiry_date')
    op.drop_column('FLEET', 'permit_expiry_date')
    op.drop_column('FLEET', 'insurance_expiry_date')
    op.drop_column('FLEET', 'rc_expiry_date')
    # ### end Alembic commands ###
