"""auto_20260512_175505

Revision ID: 750174a538b4
Revises: e72fed7e2901
Create Date: 2026-05-12 17:55:15.372164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750174a538b4'
down_revision: Union[str, Sequence[str], None] = 'e72fed7e2901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BOOKING', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('BOOKING', sa.Column('owner_response_deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BOOKING', 'owner_response_deadline')
    op.drop_column('BOOKING', 'rejection_reason')
    # ### end Alembic commands ###
