"""auto_20260511_214847

Revision ID: 7f06dc1a06ed
Revises: 71c2e3ff6c14
Create Date: 2026-05-11 21:48:50.822128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f06dc1a06ed'
down_revision: Union[str, Sequence[str], None] = '71c2e3ff6c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('FLEET', sa.Column('permit_url', sa.String(length=500), nullable=True))
    op.add_column('FLEET', sa.Column('puc_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('FLEET', 'puc_url')
    op.drop_column('FLEET', 'permit_url')
    # ### end Alembic commands ###
