"""add_owner_kyc_table

Revision ID: a9dd4ed1645b
Revises: 7a4876a11b6e
Create Date: 2026-05-09 16:28:03.837736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a9dd4ed1645b'
down_revision: Union[str, Sequence[str], None] = '7a4876a11b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OWNER_KYC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('address_1', sa.String(length=255), nullable=False),
    sa.Column('address_2', sa.String(length=255), nullable=True),
    sa.Column('address_3', sa.String(length=255), nullable=True),
    sa.Column('driving_license_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id_url', sa.String(length=500), nullable=True),
    sa.Column('otp_verified', sa.String(length=5), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', name='kycstatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.create_index(op.f('ix_OWNER_KYC_id'), 'OWNER_KYC', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OWNER_KYC_id'), table_name='OWNER_KYC')
    op.drop_table('OWNER_KYC')
    # ### end Alembic commands ###
