"""auto_20260511_220144

Revision ID: c307374004d7
Revises: 5c8ef3ac5d6d
Create Date: 2026-05-11 22:01:47.051461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c307374004d7'
down_revision: Union[str, Sequence[str], None] = '5c8ef3ac5d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CUSTOMER_KYC', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('CUSTOMER_KYC', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('CUSTOMER_KYC', sa.Column('zip_code', sa.String(length=10), nullable=True))
    op.drop_column('CUSTOMER_KYC', 'address_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CUSTOMER_KYC', sa.Column('address_3', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('CUSTOMER_KYC', 'zip_code')
    op.drop_column('CUSTOMER_KYC', 'state')
    op.drop_column('CUSTOMER_KYC', 'city')
    # ### end Alembic commands ###
