"""auto_20260513_183721

Revision ID: f2a46b53a659
Revises: f9210caf50d7
Create Date: 2026-05-13 18:37:24.050487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a46b53a659'
down_revision: Union[str, Sequence[str], None] = 'f9210caf50d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NOTIFICATION_LOG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient_mobile', sa.String(length=15), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_NOTIFICATION_LOG_id'), 'NOTIFICATION_LOG', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_NOTIFICATION_LOG_id'), table_name='NOTIFICATION_LOG')
    op.drop_table('NOTIFICATION_LOG')
    # ### end Alembic commands ###
