"""auto_20260512_213405

Revision ID: f725854b0fd2
Revises: 622d4f8c37b0
Create Date: 2026-05-12 21:34:14.491359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f725854b0fd2'
down_revision: Union[str, Sequence[str], None] = '622d4f8c37b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RATE_CARD',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('distance_from_km', sa.Float(), nullable=False),
    sa.Column('distance_to_km', sa.Float(), nullable=True),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('rate_per_km', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RATE_CARD_id'), 'RATE_CARD', ['id'], unique=False)
    op.create_table('INVOICE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('customer_kyc_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('waiting_charges', sa.Float(), nullable=False),
    sa.Column('toll_charges', sa.Float(), nullable=False),
    sa.Column('loading_charges', sa.Float(), nullable=False),
    sa.Column('total_before_gst', sa.Float(), nullable=False),
    sa.Column('gst_type', sa.String(length=10), nullable=False),
    sa.Column('cgst_rate', sa.Float(), nullable=False),
    sa.Column('sgst_rate', sa.Float(), nullable=False),
    sa.Column('igst_rate', sa.Float(), nullable=False),
    sa.Column('cgst_amount', sa.Float(), nullable=False),
    sa.Column('sgst_amount', sa.Float(), nullable=False),
    sa.Column('igst_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('invoice_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['BOOKING.id'], ),
    sa.ForeignKeyConstraint(['customer_kyc_id'], ['CUSTOMER_KYC.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_INVOICE_id'), 'INVOICE', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_INVOICE_id'), table_name='INVOICE')
    op.drop_table('INVOICE')
    op.drop_index(op.f('ix_RATE_CARD_id'), table_name='RATE_CARD')
    op.drop_table('RATE_CARD')
    # ### end Alembic commands ###
