"""auto_20260512_215716

Revision ID: fc5f050541f1
Revises: f725854b0fd2
Create Date: 2026-05-12 21:57:23.636221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc5f050541f1'
down_revision: Union[str, Sequence[str], None] = 'f725854b0fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CANCELLATION_LOG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('cancelled_by', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('hours_before_pickup', sa.Float(), nullable=False),
    sa.Column('cancellation_charge_pct', sa.Float(), nullable=False),
    sa.Column('cancellation_charge_amount', sa.Float(), nullable=False),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('refund_status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['BOOKING.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_CANCELLATION_LOG_id'), 'CANCELLATION_LOG', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CANCELLATION_LOG_id'), table_name='CANCELLATION_LOG')
    op.drop_table('CANCELLATION_LOG')
    # ### end Alembic commands ###
